print('An added line')

print('W1 Q1 r-project.org')
print('W! Q2 Every year')
print('W1 Q5 f[3]') 
print('W1 Q3 install.packages("sweSCB")')
print('W1 Q4 hist(f)')
print('W1 Q6 f[3] <-2.3  WRONG?? !!')
print('blah, blah, blah.')
print('W1 Q7')
 5:15
seq(5,15,1)
print('W1 Q8')
 sample(letters, 5, replace=T)
 sample(letters, 5, replace=F)
 sample(LETTERS, 5, replace=F)
print('W1 Q9')
 a <-sample(letters[1:4],100, replace=T)
 pie(table(a))
print('W1 Q10')
 length <- rnorm(10, 180, 10)
 weight <- (length/100)^2 * 25
 measurements <- data.frame(cbind(length, weight))
 measurements<-round(measurements)